import babel from '@rollup/plugin-babel';
import commonjs from '@rollup/plugin-commonjs';
import replace from '@rollup/plugin-replace';
import uglify from '@lopatnov/rollup-plugin-uglify';
import css from 'rollup-plugin-css-only';

export default {
  input: 'src/index.js',
  external: [
    'react',
    'react-dom',
    'prop-types',
    '@mui/material/Paper',
    '@mui/material/Table',
    '@mui/material/Tooltip',
    '@mui/material/Button',
    '@mui/material/Checkbox',
    '@mui/material/FormControl',
    '@mui/material/FormControlLabel',
    '@mui/material/FormGroup',
    '@mui/material/Grid',
    '@mui/material/Input',
    '@mui/material/InputLabel',
    '@mui/material/ListItemText',
    '@mui/material/MenuItem',
    '@mui/material/Select',
    '@mui/material/TextField',
    '@mui/material/Typography',
    '@mui/material/TableCell',
    '@mui/material/TableRow',
    '@mui/material/TableBody',
    '@mui/material/TableHead',
    '@mui/material/TableFooter',
    '@mui/material/TablePagination',
    '@mui/material/TableSortLabel',
    '@mui/material/IconButton',
    '@mui/material/Popover',
    '@mui/material/Menu',
    '@mui/material/ListItemIcon',
    '@mui/material/Toolbar',
    '@mui/material/Grow',
    '@mui/material/Chip',
    '@mui/material/InputBase',
    '@mui/icons-material/Search',
    '@mui/icons-material/Clear',
    '@mui/icons-material/Delete',
    '@mui/icons-material/Help',
    '@mui/icons-material/Close',
    '@mui/icons-material/CloudDownload',
    '@mui/icons-material/Print',
    '@mui/icons-material/ViewColumn',
    '@mui/icons-material/FilterList',
    '@mui/icons-material/FileDownload',
    '@mui/icons-material/PictureAsPdf',
    '@mui/icons-material/TableChart',
    '@mui/icons-material/KeyboardArrowRight',
    '@mui/icons-material/Remove',
    'tss-react/mui',
    'clsx',
    'lodash.assignwith',
    'lodash.clonedeep',
    'lodash.find',
    'lodash.isequal',
    'lodash.isundefined',
    'lodash.merge',
    'react-dnd',
    'react-dnd-html5-backend',
    'html2canvas',
    'jspdf',
  ],
  plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify('production'),
      preventAssignment: true,
    }),
    commonjs({
      include: ['node_modules/**'],
    }),
    babel({
      babelHelpers: 'runtime',
      babelrc: true,
      exclude: ['**/*.css'],
    }),
    css({
      output: 'bundle.css',
    }),
    uglify({
      compress: {
        conditionals: true,
        unused: true,
        comparisons: true,
        sequences: true,
        dead_code: true,
        evaluate: true,
        if_return: true,
        join_vars: true,
      },
      output: {
        comments: false,
      },
    }),
  ],
  output: [
    {
      file: 'dist/index.cjs',
      format: 'cjs',
      exports: 'named',
      sourcemap: true,
    },
    {
      file: 'dist/index.esm.js',
      format: 'esm',
      sourcemap: true,
    },
    {
      file: 'dist/index.js',
      format: 'cjs',
      exports: 'named',
      sourcemap: true,
    },
  ],
};
